apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: todo-list
  labels:
    app: keys-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 5
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: api
    spec:
      hostAliases:
        - ip: "192.168.1.67"
          hostnames:
            - "cob.cobden.net"
      imagePullSecrets:
        - name: docker-registry-secret
      containers:
        - name: api
          image: containers.chewed-k8s.net/todo-list/api:latest
          imagePullPolicy: Always
          readinessProbe:
            httpGet:
              path: /health
              port: 80
          ports:
            - containerPort: 80
          env:
            - name: VAULT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: api-secrets
                  key: vault-token
            - name: MONGO_ACCOUNT_COLLECTION
              valueFrom:
                secretKeyRef:
                  name: api-secrets
                  key: mongo-account-collection
            - name: MONGO_LIST_COLLECTION
              valueFrom:
                secretKeyRef:
                  name: api-secrets
                  key: mongo-list-collection
            - name: MONGO_DB
              valueFrom:
                secretKeyRef:
                  name: api-secrets
                  key: mongo-db
            - name: MONGO_HOST
              valueFrom:
                secretKeyRef:
                  name: api-secrets
                  key: mongo-host
            - name: MONGO_VAULT_PATH
              valueFrom:
                secretKeyRef:
                  name: api-secrets
                  key: mongo-vault-path
            - name: VAULT_HOST
              valueFrom:
                secretKeyRef:
                  name: api-secrets
                  key: vault-host

---
apiVersion: v1
kind: Service
metadata:
  name: api
  namespace: todo-list
  labels:
    app: api
spec:
  ports:
    - port: 3000
      protocol: TCP
      targetPort: 80
  selector:
    app: api

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: api
  namespace: todo-list
  annotations:
    cert-manager.io/cluster-issuer: live-issuer
    nginx.ingress.kubernetes.io/rewrite-target: /$2
  labels:
    app: api
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - api.todo-list.app
      secretName: api-service-tls
  rules:
    - host: api.todo-list.app
      http:
        paths:
          - path: /v1(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: api
                port:
                  number: 80
